St olga ivanova lesson 3 level 5
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #106
Opened 2022-09-07 10:54 UTC by 0lgaIvanova

2022-09-07 18:14 UTC, daniilsjb commented on src/main/java/students/olga_ivanova/_lesson_3/level_5/Dog.java
> +    public void voice() {System.out.println("Lord - Lord - Lord");
У собаки может быть другое имя, Lord - это только один возможный случай. Если создать собачку с другим именем и вызвать этот метод, то результат будет неправильный. Непорядок! Чтобы исправить, нужно выводить содержимое переменной `this.name`, трижды. Подскажу: здесь можно использовать оператор `+`.

2022-09-08 11:05 UTC, daniilsjb requested changes
Если возникают какие-либо вопросы про задания или что-то не получается, можно мне писать в Телеграме напрямую (или оставлять комментарии здесь). Задания про классы бывают нетривиальны 😄

2022-09-08 11:05 UTC, daniilsjb commented on src/main/java/students/olga_ivanova/_lesson_3/level_5/DogDemo.java
> +        dog.changeColor("Beige");
`voice4()` стоит вызывать после изменения цвета. Вывод в консоли должен отражать тот факт, что текущий цвет собаки - `Beige`, а не `Black`.

2022-09-09 10:13 UTC, 0lgaIvanova commented on src/main/java/students/olga_ivanova/_lesson_3/level_5/Dog.java
> +    void voice1() {System.out.println(" name " + " name " + " name " );}
Спасибо за подробный коментарий! Теперь всё поняла ))) исправила, должно быть ок.

2022-09-09 10:27 UTC, 0lgaIvanova commented on src/main/java/students/olga_ivanova/_lesson_3/level_5/Dog.java
> +    void voice1() {System.out.println(" name " + " name " + " name " );}
Обычно когда я начинаю делать задания , у меня миллион вопросов, но я стараюсь читать материалы или гуглить, чтоб разобраться что к чему. Чтоб Вы понимали, я полный ноль в программировании ))) но мне интересно )). Буду стараться больше спрашивать у Вас.

2022-09-10 08:06 UTC, daniilsjb commented on src/main/java/students/olga_ivanova/_lesson_3/level_5/Dog.java
> +    void voice1() {System.out.println(" name " + " name " + " name " );}
Рад помочь! Все с чего-то начинают 😄

2022-09-10 08:06 UTC, daniilsjb approved these changes
Отлично! 🚀

2022-09-10 08:06 UTC, merged