lesson 4 level 6 task 16
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #327
Opened 2022-10-09 06:31 UTC by ArtemijsTalamajevs

2022-10-09 17:33 UTC, daniilsjb requested changes

2022-10-09 17:33 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_4/level_6/Stock.java
> +
Изначально `minPrice` и `maxPrice` тоже должны быть равны `currentPrice`.

2022-10-09 17:33 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_4/level_6/StockTest.java
> +        assertThatEquals(actual, expected, description);
Собственно, поэтому тут проваливается тест 🧐

2022-10-09 18:19 UTC, ArtemijsTalamajevs commented on src/main/java/students/artemijs_talamajevs/lesson_4/level_6/Stock.java
> +
Поправил файл с стоком

2022-10-10 15:17 UTC, daniilsjb approved these changes

2022-10-10 15:17 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_4/level_6/Stock.java
> +        maxPrice=currentPrice;
Не забывайте ставить вокруг `=` пробелы 🙂

2022-10-10 15:17 UTC, merged