St olga ivanova lesson 7 level 7 task 13
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #366
Opened 2022-10-17 08:42 UTC by 0lgaIvanova

2022-10-17 17:40 UTC, daniilsjb requested changes

2022-10-17 17:40 UTC, daniilsjb commented on src/main/java/students/olga_ivanova/lesson_7/level_7/task_13/UserEntityRepository.java
> +        user.getPersonalCode(personalCode);
Думаю, здесь везде должно быть `set` вместо `get`. К слову, геттеры обычно не принимают параметры 🧐

2022-10-18 08:20 UTC, 0lgaIvanova commented on src/main/java/students/olga_ivanova/lesson_7/level_7/task_13/UserEntityRepository.java
> +        user.getPersonalCode(personalCode);
> Думаю, здесь везде должно быть `set` вместо `get`. К слову, геттеры обычно не принимают параметры 🧐

Исправила на set.

2022-10-18 08:21 UTC, 0lgaIvanova commented on src/main/java/students/olga_ivanova/lesson_7/level_7/task_13/UserEntityRepository.java
> +        user.getPersonalCode(personalCode);
Я сделала тесты, но тест update и delete у меня не получаются :(
подскажите пожалуйста.

2022-10-18 18:14 UTC, daniilsjb commented on src/main/java/students/olga_ivanova/lesson_7/level_7/task_13/UserRepositoryTest.java
> +        if (Objects.equals(actual, expected)) {
Тут сравниваются строки с `UserEntity`, а такая проверка не имеет смысла. На текущий момент тесты проходят только потому, что ожидаемый и настоящий результат всегда `null` (то есть настоящий тип значения даже не играет роли).

Важно понимать, что тесты могут состоять из нескольких шагов. Например, чтобы прочитать из репозитории пользователя, его сперва нужно сохранить. Аналогично при удалении и обновлении. Ведь изначально в репозитории нет, так кого же тогда удалять? 🤔

Например, вот как я вижу возможное использование этой репозитории:

```java
public void userEnttiyRepositoryTest1() {
    UserEntityRepository subject = new UserEntityRepository(32);
    UserEntity user = new UserEntity(1, "Seoman", "Snowlock", "123456");

    // После этого этапа пользователь должен появиться в репозитории и быть доступным.
    subject.save(user);

    UserEntity actual = subject.getById(1);
    UserEntity expected = user;

    assertThatEquals(actual, expected, "Should be possible to get an existing user by id.");
}
```

Со штуками типа обновления/удаления несколько сложнее, поскольку эти методы сейчас ничего не возвращают. Но даже в таком случае их можно протестировать: достаточно подумать над эффектом, который они должны иметь над репозиторией. Скажем, если я удалю из репозитории существующего пользователя, то у меня больше не должно быть возможности его найти:

```java
public void userEnttiyRepositoryTest2() {
    UserEntityRepository subject = new UserEntityRepository(32);
    UserEntity user = new UserEntity(1, "Seoman", "Snowlock", "123456");

    // Предположим, что save уже работает корректно (это проверяют другие тесты).
    subject.save(user);

    // После этого этапа пользователя больше нет в репозитории
    subject.delete(user);

    UserEntity actual = subject.getById(1);
    UserEntity expected = null;

    assertThatEquals(actual, expected, "Should be possible to delete an existing user.");
}
```

2022-10-20 14:49 UTC, daniilsjb approved these changes
🙂👍

2022-10-20 14:49 UTC, merged