lesson 7 level  5
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #412
Opened 2022-10-23 17:46 UTC by ArtemijsTalamajevs

2022-10-23 18:16 UTC, daniilsjb requested changes

2022-10-23 18:16 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_7/level_5/PowerCalculator.java
> +    }
В задании требуется реализовать операцию самостоятельно при помощи цикла (штуки типа отрицательных степеней можно не учитывать). На практике, конечно, лучше использовать `Math.pow()`, но всё-таки тут вопрос в практике 🙂

2022-10-24 16:57 UTC, ArtemijsTalamajevs commented on src/main/java/students/artemijs_talamajevs/lesson_7/level_5/PowerCalculator.java
> +    }
переделал

2022-10-24 17:42 UTC, daniilsjb approved these changes
Супер 👍

2022-10-24 17:42 UTC, merged