lesson 10 level  2
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #430
Opened 2022-10-30 15:59 UTC by ArtemijsTalamajevs

Не могу тест написать по имплементации (( Не знаю как он должен выглядеть правильно(

2022-10-30 20:05 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/DayOfTheWeekDetectorTest.java
> +    };
На каждую реализацию нужно написать отдельный набор тестов, проверяющий каждый возможный результат метода `detectDayName()`. Реализаций у нас две - одна основана на `switch`, другая на `if`. В данном случае IntelliJ предложила вам создать анонимную реализацию, здесь  этого делать _не нужно_. Код должен будет выглядеть примерно так:

```java
class IfDayOfTheWeekDetectorTest {
    private DayOfTheWeekDetector subject = new IfDayOfTheWeekDetector();

    public static void main(String[] args) {
        IfDayOfTheWeekDetectorTest test = new IfDayOfTheWeekDetectorTest();
        test.scenario1();
        test.scenario2();
        ...
    }

    private void scenario1() {
        assertThatEquals(subject.detectDayName(1), "Monday");
    }

    private void scenario2() {
        assertThatEquals(subject.detectDayName(2), "Tuesday");
    }

    ...

    // метод assertThatEquals создайте сами, тут ничего нового
}

// аналогично создайте класс SwitchDayOfTheWeekDetectorTest. Естественно, в нём
// нужно проверять функционал класса SwitchDayOfTheWeekDetector.
```

2022-10-31 17:02 UTC, ArtemijsTalamajevs commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/DayOfTheWeekDetectorTest.java
> +    };
Запушил повторно .Я думал как положить в один класс для теста If  и Swich изначально,но не знал что их нужно было разделить  на 2 теста.

2022-10-31 19:24 UTC, daniilsjb requested changes

2022-10-31 19:24 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/IfDayOfTheWeekDetectorTest.java
> +    }
Уже лучше, но единственное - тестов нужно написать по одному сценарию на каждый день недели (и ещё один для несуществующего дня). К счастью, у каждой реализации набор тестов будет одинаковый, отличается только сама реализация 🙂

2022-10-31 19:24 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/IfDayOfTheWeekDetectorTest.java
> +
На конце файлов лишние пустые строки лучше убирать.

2022-11-01 19:34 UTC, daniilsjb approved these changes

2022-11-01 19:34 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/IfDayOfTheWeekDetectorTest.java
> +    }
Я имел ввиду, что должен быть сценарий с несуществующим днём недели, где ожидается строка `Please input a valid number between 1 and 7` 😅

2022-11-01 19:34 UTC, merged

2022-11-02 07:08 UTC, ArtemijsTalamajevs commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_2/IfDayOfTheWeekDetectorTest.java
> +    }
Ой .Я забыл в Descripte написать эту строку .А написал это (