lesson 10 level  3
konstantins-buts/jg-java-1-online-autumn-thursday-2022 pull request #465
Opened 2022-11-05 17:59 UTC by ArtemijsTalamajevs

В таске 8 проблема ,ошибок нету ,но пишет ошибку при компиляции null .Нужно что то сделать с Optional в этом задании ? Не пойму =/

2022-11-06 10:07 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/InMemoryProductRepository.java
> +    }
Да, так можно - это даже ожидаемое решение при использовании массивов. Мы создаём новый массив с длинной на единицу больше старого, копируем туда все старые элементы, а новый добавляем на конец. Единственная ошибка, во второй строчке присвоение должно работать наоборот: нам нужно записать `product` в последнюю ячейку массива 🙂

Про `ArrayRange`, вы имеете ввиду [`Arrays.copyOfRange()`](https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#copyOfRange(T[],%20int,%20int))? Основное его отличие от `copyOf()` заключается в том, что в нём можно копировать начиная с любого элемента, а не только с начала массива. Здесь нам это сильно не поможет, поскольку нам всё равно нужно скопировать все элементы старого массива целиком.

2022-11-06 10:07 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/ProductRepositoryTest.java
> +    }
Почему при поиске продукта под названием `Apple` мы ожидаем найти продукт под названием `Quince`? 🤔

2022-11-06 10:07 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/Ruler.java
> +public interface Ruler<W, H> {
`public` надо убрать.

2022-11-06 10:19 UTC, ArtemijsTalamajevs commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/ProductRepositoryTest.java
> +    }
А вот и ошибка  )) Я не заметтил ,что копипейстнул не ту строчку

2022-11-07 16:57 UTC, daniilsjb requested changes

2022-11-07 16:57 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/Product.java
> +}
Забыл ещё про один момент, тут нужно сгенерировать методы `equals()` и `hashCode()`. Также, стоит убрать лишний `import`.

2022-11-07 16:57 UTC, daniilsjb commented on src/main/java/students/artemijs_talamajevs/lesson_10/level_3/ProductRepositoryTest.java
> +        if (expected == actual) {
А здесь нужно использовать метод `.equals()` вместо оператора `==`, поскольку нам нужно сравнивать содержимое, а не ссылки.

2022-11-10 19:52 UTC, daniilsjb approved these changes
👍

2022-11-10 19:53 UTC, merged